# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0002_auto_20170823_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookauth',
            name='mbed_cloud_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livedevice.MBEDCloudAccount'),
        ),
    ]
