# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('livedevice', '0003_auto_20170823_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='wemSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=10)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='mbedcloudaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookauth',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
