# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0004_auto_20170824_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FOTAPortalSite',
            new_name='SiteScheme',
        ),
    ]
