# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0005_auto_20170824_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbedcloudaccount',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mbedcloudaccount',
            name='connected_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitescheme',
            name='scheme',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=10),
        ),
    ]
