# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0006_auto_20170824_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbedcloudaccount',
            options={'verbose_name': 'MBED Cloud account'},
        ),
        migrations.AlterField(
            model_name='mbedcloudaccount',
            name='api_key',
            field=models.CharField(max_length=150, unique=True, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='mbedcloudaccount',
            name='url',
            field=models.URLField(default='https://api.us-east-1.mbedcloud.com', verbose_name='URL'),
        ),
    ]
