# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0007_auto_20170825_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookauth',
            name='mbed_cloud_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livedevice.MBEDCloudAccount'),
        ),
    ]
