# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedevice', '0008_auto_20170911_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbedcloudaccount',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='mbedcloudaccount',
            name='connected_details',
        ),
    ]
